### ISSUE TITLE
EPIC: Consensus-to-Block node integration

### ISSUE THREAD

**Issue by jsync-swirlds** [hiero-ledger/hiero-block-node#170]
This epic consists of designing, testing, and verifying the integration between consensus node and block node when a consensus node is publishing a block stream to a block node.

Tech Notes:

1. Use Local Node for integration testing. 
1. Slow down consensus traffic in local node else we will get blocks every ms, or less, because CN sends blocks for every round.
   - Round time depends on latency, and is ~1s in Mainnet, but is <10ms on testnet (local network), and may be sub μs on local node (same physical machine).
1. Local node can generate different types of transactions using Mirror Node, Simulator Client, and SDK(s).
   - Prefer Mirror Node over Simulator over SDK(s) based on client priority and timelines.

### Block Node Tasks
- [ ] #120
- [ ] https://github.com/hashgraph/hedera-block-node/issues/418
- [ ] https://github.com/hashgraph/hedera-block-node/issues/519
- [ ] https://github.com/hashgraph/hedera-block-node/issues/532
- [ ] https://github.com/hashgraph/hedera-block-node/issues/535
- [ ] https://github.com/hashgraph/hedera-block-node/issues/533
- [ ] https://github.com/hashgraph/hedera-block-node/issues/534
- [ ] Establish an integration environment (single server?) for testing
- [ ] https://github.com/hashgraph/hedera-block-node/issues/417
- [ ] Adjust protocol so that acknowledgement is only for success and non-success is always EndOfStream response.
- [ ] https://github.com/hashgraph/hedera-block-node/issues/573

Consensus Node services team will track associated work on consensus node in a [mirror epic](https://github.com/hashgraph/hedera-services/issues/15428).

**Comment by AlfredoG87** [comment]
should we add a task for consensus node to connect to the block-node?

**Comment by AlfredoG87** [comment]
should the`link` on the `mirror epic` for CN be a similar story on services repo, is pointing to the same right now.
