### ISSUE TITLE
Block Stream HIP

### ISSUE THREAD

**Issue by Nana-EC** [hiero-ledger/hiero-block-node#37]
### Problem

Currently no HIP exists to define Block streams

### Solution

Create Block Stream HIP
- [x] Draft HIP
- [x] Early socialization w DAs
- [x] Early socialization w PMs
- [x] Early socialization w architects
- [x] Early socialization w affected team leads/managers
- [ ] Address socialization feedback
- [ ] Round(s) of official reviews
- [x] Publish HIP
- [ ] Merge HIP

### Remaining Open Questions
- [x] Add Round Header to [Block image](https://www.notion.so/swirldslabs/Draft-Block-Streams-HIP-f1f260d8a54c404a96be4051c4292f62?pvs=4#10d7c9ab25918016a979d557b3c6348b)
- [ ] Nana [comment about "Known"](https://www.notion.so/Draft-Block-Streams-HIP-f1f260d8a54c404a96be4051c4292f62?d=10c7c9ab25918069adf2001c1d1f7013&pvs=4#b5a46966f37f4780b48256c9a68b3fcd)
- [x] Neeha's question about [Block Proof and freeze round](https://www.notion.so/Draft-Block-Streams-HIP-f1f260d8a54c404a96be4051c4292f62?d=1027c9ab259180659f7d001cf679ff87&pvs=4#bbec2c837a4440cea7a2a3b099ae4c02)
- [x] Nana's question about [block versus block item streams](https://www.notion.so/Draft-Block-Streams-HIP-f1f260d8a54c404a96be4051c4292f62?d=10c7c9ab2591807fa7c9001c0863b4f9&pvs=4#788c433f68864e99936fbbb7d12d2542)
- [x] Jasper's question about [round judges](https://www.notion.so/Draft-Block-Streams-HIP-f1f260d8a54c404a96be4051c4292f62?d=2d6f6fd42a5643059839dc4f9c9d297c&pvs=4#f9cb4a38e240475cb42ae73804c53ec3)
- [x] Jasper's question about [first transaction consensus time](https://www.notion.so/swirldslabs/Draft-Block-Streams-HIP-f1f260d8a54c404a96be4051c4292f62?pvs=4#e05442bf6b534bf8ba5da58adbeb2af7) (This may be answered, effectively, as it's implemented in services code).
- [x] Possibility to [remove exchange rate from the `TransactionResult` message](https://www.notion.so/Draft-Block-Streams-HIP-f1f260d8a54c404a96be4051c4292f62?d=3ac3fafc95214f4dae34228a08230b9f&pvs=4#8118accf50d84d1094cab3593b40b7b5)
- [ ] Document [final decision and reasoning for keeping `TransferList`](https://www.notion.so/Draft-Block-Streams-HIP-f1f260d8a54c404a96be4051c4292f62?d=3ac3fafc95214f4dae34228a08230b9f&pvs=4#8118accf50d84d1094cab3593b40b7b5).
- [ ] Final decision (Richard and Jasper) on whether to [add an open string error message or use a sub-code (defined on a per-response-code basis)](https://www.notion.so/swirldslabs/Draft-Block-Streams-HIP-f1f260d8a54c404a96be4051c4292f62?pvs=4#e7559dc15cbe49d0aa7d57dca1bca8fe).  Note, there is an extensive comment discussion, but it's lost in the Notion edits.
- [ ] Resolve request to [possibly rename EthereumOutput](https://www.notion.so/Draft-Block-Streams-HIP-f1f260d8a54c404a96be4051c4292f62?d=10c7c9ab25918084bb06001c7aa72b4c&pvs=4#aa364bef829c4c97bf612edcef9254df)
- [ ] Resolve the open [design question about splitting accounts](https://www.notion.so/swirldslabs/Draft-Block-Streams-HIP-f1f260d8a54c404a96be4051c4292f62?pvs=4#2865dd6ca2a54af9b77d9a42d58d85e5)
   - Note, this is a major item, and not one we can reasonably change _after_ Block Streams are in mainnet.
   - Additional detail [in comments](https://www.notion.so/Draft-Block-Streams-HIP-f1f260d8a54c404a96be4051c4292f62?d=10c7c9ab25918006a946001c8697d2ad&pvs=4#48f2308b44dd45238a91c5af546ede78).
- [ ] Have Michael Tinker validate the block hash calculation and [resolve the todo](https://www.notion.so/swirldslabs/Draft-Block-Streams-HIP-f1f260d8a54c404a96be4051c4292f62?pvs=4#ca664f109cdb473494e9c561f10d5528) as requested in [this comment](https://www.notion.so/Draft-Block-Streams-HIP-f1f260d8a54c404a96be4051c4292f62?d=8272558f555344278d0a44ac54fe9db6&pvs=4#ca664f109cdb473494e9c561f10d5528)

### Follow up tasks
- [ ] Create a [marketing/communications plan for pre-release](https://www.notion.so/Draft-Block-Streams-HIP-f1f260d8a54c404a96be4051c4292f62?d=10e7c9ab2591805fa1f6001c544f75a2&pvs=4#7389744c123d4134afaa0788934064ef) including [preview release](https://www.notion.so/Draft-Block-Streams-HIP-f1f260d8a54c404a96be4051c4292f62?d=10e7c9ab259180b4b0ad001cc090bf97&pvs=4#3a14281b39d74d17b52ee898a76ef557) information and [developer-specific information](https://www.notion.so/Draft-Block-Streams-HIP-f1f260d8a54c404a96be4051c4292f62?d=10e7c9ab259180579d7e001ca894ac6c&pvs=4#3a14281b39d74d17b52ee898a76ef557).
- [ ] Document the plan for [writing block stream to buckets](https://www.notion.so/swirldslabs/Draft-Block-Streams-HIP-f1f260d8a54c404a96be4051c4292f62?pvs=4#6e0b40c60a884c7ca5d9c06dbd516fe7) and [possibly move to "how to teach" or a separate document](https://www.notion.so/Draft-Block-Streams-HIP-f1f260d8a54c404a96be4051c4292f62?d=8c68c02783584d4bbfb671072532c899&pvs=4#6e0b40c60a884c7ca5d9c06dbd516fe7)
- [ ] Create and manage a task to [document redaction and errata using `FilteredBlockItem`](https://www.notion.so/swirldslabs/Draft-Block-Streams-HIP-f1f260d8a54c404a96be4051c4292f62?pvs=4#9f34b71ba32a4425a7e60a9f94ada04b)
- [ ] Create and manage a task to [document the algorithm for translating states into a merkle tree](https://www.notion.so/swirldslabs/Draft-Block-Streams-HIP-f1f260d8a54c404a96be4051c4292f62?pvs=4#e481f7ada3154aaaaa219303b0c9660d)
- [ ] Include as many "rejected" ideas as possible in the [rejected ideas section](https://www.notion.so/swirldslabs/Draft-Block-Streams-HIP-f1f260d8a54c404a96be4051c4292f62?pvs=4#10e7c9ab25918033b105d894afde888a)
- [ ] Resolve any remaining open issues and move [inline questions](https://www.notion.so/swirldslabs/Draft-Block-Streams-HIP-f1f260d8a54c404a96be4051c4292f62?pvs=4#361ca6abb79e4c56b858f5760104fef0) into open issues for visibility and transparency.
- [ ] Clean up and complete the [links section](https://www.notion.so/swirldslabs/Draft-Block-Streams-HIP-f1f260d8a54c404a96be4051c4292f62?pvs=4#10c7c9ab2591800dae54e6e4d7272de8)

> Note: Tasklist not used because it has a short line limit, which fails on notion links

**Comment by jasperpotts** [comment]
HIP-1056 PR has now been created https://github.com/hashgraph/hedera-improvement-proposal/pull/1056

**Comment by jsync-swirlds** [comment]
Closing this as complete now that the HIP is approved for Hiero and merged.
