### ISSUE TITLE
[Initiative] Low Latency BS Extraction

### ISSUE THREAD

**Issue by Nana-EC** [hiero-ledger/hiero-block-node#395]
### Phase 2 Tasks
- [ ] https://github.com/hashgraph/hedera-block-node/issues/403
- [ ] https://github.com/hashgraph/hedera-block-node/issues/368
- [ ] https://github.com/hashgraph/hedera-block-node/issues/341

### Phase 3 Tasks
- [ ] EPIC: Filter block stream
- [ ] EPIC: Enhanced Mirror Node integration
