### ISSUE TITLE
Longevity test for Consuming Block Stream

### ISSUE THREAD

**Issue by a-saksena** [hiero-ledger/hiero-block-node#417]
### Tasks
- [ ] https://github.com/hashgraph/hedera-block-node/issues/440
- [ ] https://github.com/hashgraph/hedera-block-node/issues/441
- [ ] https://github.com/hashgraph/hedera-block-node/issues/437
- [ ] https://github.com/hashgraph/hedera-block-node/issues/438
